# -*- coding: utf-8 -*-
"""Cross-Market Analysis: Crypto, Oil & Stocks with SQL and Streamlit(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWR2dFw6cqlGQ2-NdZMI2c8Zjf1hT0oz
"""

!pip install requests

import requests
import time

all_records = []

for page in range(1, 6):
    url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page={page}&sparkline=False"
    params = {
        "vs_currency": "inr",
        "order": "market_cap_desc",
        "per_page": 250,
        "page": page,
        "sparkline": False
    }

    response = requests.get(url, params=params)

    if response.status_code == 200:
        data = response.json()
        all_records.extend(data)
        print(f"Page {page} fetched successfully: {len(data)} records")
    else:
        print(f"Page {page} failed with status {response.status_code}")
        print("Waiting and retrying...")
        time.sleep(10)
        continue


    time.sleep(1)

all_records

import pandas as pd
crypto_df = pd.DataFrame(all_records)
crypto_df.head()

crypto_df.columns

len(all_records)

crypto_df = crypto_df[["id", "symbol", "name", "current_price", "market_cap", "market_cap_rank", "total_volume", "circulating_supply", "total_supply", "ath", "atl", "last_updated"]]

crypto_df

crypto_df["last_updated"] = pd.to_datetime(crypto_df["last_updated"]).dt.date
crypto_df.head()

crypto_df.info()

coin_ids = ("bitcoin", "ethereum", "tether")
all_data = []

for coin_id in coin_ids:
  url = f"https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=inr&days=365"
  params = {
      "vs_currency": "inr",
      "days": "365",
  }
  response = requests.get(url, params=params)
  data = response.json()

  df = pd.DataFrame(data["prices"], columns=["timestamp", "price"])

  df["date"] = pd.to_datetime(df["timestamp"], unit="ms").dt.date
  df["coin_id"] = coin_id
  df = df[["coin_id", "date", "price"]]
  df.rename(columns={"price": "price_inr"}, inplace=True)

  all_data.append(df)

combine3coins_df = pd.concat(all_data, ignore_index=True)

combine3coins_df

combine3coins_df.head()

"""Oil Price"""

import pandas as pd
oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")
oil_df

oil_df.to_csv("oil_prices.csv",index = False)

import pandas as pd
oil_df = pd.read_csv("oil_prices.csv")
oil_df

oil_df["Date"] = pd.to_datetime(oil_df["Date"])
oil_df = oil_df[
    (oil_df["Date"] >= "2020-01-01") & (oil_df["Date"] <= "2026-01-31")
]
oil_df

"""Stock Prices (Yahoo Finance API)



"""

import yfinance as yf
import pandas as pd

tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-01-12"

stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df.head()

# Process ^NSEI
nsei_df = stocks_df['^NSEI'].reset_index()
nsei_df['ticker'] = '^NSEI'
nsei_df = nsei_df.dropna(subset=['Close'])  # Handle NULLs
nsei_df.columns = ['date', 'open', 'high', 'low', 'close', 'volume', 'ticker']
print(f"^NSEI: {len(nsei_df)} rows")

# Process ^IXIC
ixic_df = stocks_df['^IXIC'].reset_index()
ixic_df['ticker'] = '^IXIC'
ixic_df = ixic_df.dropna(subset=['Close'])  # Handle NULLs
ixic_df.columns = ['date', 'open', 'high', 'low', 'close', 'volume', 'ticker']
print(f"^IXIC: {len(ixic_df)} rows")

# Process ^GSPC
gspc_df = stocks_df['^GSPC'].reset_index()
gspc_df['ticker'] = '^GSPC'
gspc_df = gspc_df.dropna(subset=['Close'])  # Handle NULLs
gspc_df.columns = ['date', 'open', 'high', 'low', 'close', 'volume', 'ticker']
print(f"^GSPC: {len(gspc_df)} rows")

# Concatenate all three
stocks_long_df = pd.concat([nsei_df, ixic_df, gspc_df], ignore_index=True)

# Reorder columns
stocks_long_df = stocks_long_df[['ticker', 'date', 'open', 'high', 'low', 'close', 'volume']]

print(f"\n✓ Total: {len(stocks_long_df)} rows")
print(f"✓ Date range: {stocks_long_df['date'].min()} to {stocks_long_df['date'].max()}")

# Display
print("\nFirst few rows:")
print(stocks_long_df.head())

print("\nLast few rows:")
print(stocks_long_df.tail())

print("\nRows per ticker:")
print(stocks_long_df.groupby('ticker').size())

"""SQl"""

import sqlite3


conn = sqlite3.connect('market_analysis.db')


cursor = conn.cursor()

print("✓ Database connection created!")
print("✓ Cursor is ready!")

"""1. Cryptocurrencies table"""

cursor.execute('''
    CREATE TABLE IF NOT EXISTS cryptocurrencies (
        id VARCHAR(50) PRIMARY KEY,
        symbol VARCHAR(10),
        name VARCHAR(100),
        current_price DECIMAL(18, 6),
        market_cap BIGINT,
        market_cap_rank INT,
        total_volume BIGINT,
        circulating_supply DECIMAL(20, 6),
        total_supply DECIMAL(20, 6),
        ath DECIMAL(18, 6),
        atl DECIMAL(18, 6),
        date DATE
    )
    ''')
 conn.commit()

"""2. Crypto_prices table"""

cursor.execute('''
    CREATE TABLE IF NOT EXISTS crypto_prices (
        coin_id VARCHAR(50),
        date DATE,
        price_usd DECIMAL(18, 6),
        PRIMARY KEY (coin_id, date),
        FOREIGN KEY (coin_id) REFERENCES cryptocurrencies(id)
    )
    ''')
conn.commit()

"""3. Oil_prices table"""

cursor.execute('''
    CREATE TABLE IF NOT EXISTS oil_prices (
        date DATE PRIMARY KEY,
        price_usd DECIMAL(18, 6)
    )
    ''')
conn.commit()

"""4. Stock_prices table"""

cursor.execute('''
    CREATE TABLE IF NOT EXISTS stock_prices (
        date DATE,
        ticker VARCHAR(20),
        open DECIMAL(18, 6),
        high DECIMAL(18, 6),
        low DECIMAL(18, 6),
        close DECIMAL(18, 6),
        volume BIGINT,
        PRIMARY KEY (date, ticker)
    )
    ''')

conn.commit()

"""INSERT DATA FROM DATAFRAMES"""

def insert_crypto_data(conn, crypto_df):
    """Insert cryptocurrency data"""
    # Add current date for last_updated equivalent
    crypto_df['date'] = datetime.now().strftime('%Y-%m-%d')

    # Rename columns to match SQL schema
    crypto_insert = crypto_df.rename(columns={
        'current_price': 'current_price',
        'market_cap': 'market_cap',
        'market_cap_rank': 'market_cap_rank',
        'total_volume': 'total_volume',
        'circulating_supply': 'circulating_supply',
        'total_supply': 'total_supply'
    })

    crypto_insert.to_sql('cryptocurrencies', conn, if_exists='replace', index=False)
    print(f"✓ Inserted {len(crypto_df)} cryptocurrency records")

def insert_crypto_prices(conn, combine3coins_df):
    """Insert crypto price history"""
    # Rename columns to match SQL schema
    price_data = combine3coins_df.rename(columns={
        'price_inr': 'price_usd'  # Note: adjust if you need INR to USD conversion
    })

    price_data.to_sql('crypto_prices', conn, if_exists='replace', index=False)
    print(f"✓ Inserted {len(price_data)} crypto price records")

def insert_oil_prices(conn, oil_df):
    """Insert oil price history"""
    # Rename columns to match SQL schema
    oil_data = oil_df.rename(columns={
        'Date': 'date',
        'Price': 'price_usd'
    })

    oil_data.to_sql('oil_prices', conn, if_exists='replace', index=False)
    print(f"✓ Inserted {len(oil_data)} oil price records")

def insert_stock_prices(conn, stock_df):
    """Insert stock price history - transform from wide to long format"""
    stock_long = []

    # Transform wide format to long format
    tickers = ['^IXIC', '^NSEI', '^GSPC']

    for ticker in tickers:
        ticker_data = pd.DataFrame({
            'date': stock_df['Date'],
            'ticker': ticker,
            'open': stock_df.get(f'{ticker} Open', stock_df.get('Open')),
            'high': stock_df.get(f'{ticker} High', stock_df.get('High')),
            'low': stock_df.get(f'{ticker} Low', stock_df.get('Low')),
            'close': stock_df.get(f'{ticker} Close', stock_df.get('Close')),
            'volume': stock_df.get(f'{ticker} Volume', stock_df.get('Volume'))
        })
        stock_long.append(ticker_data)

    stock_data = pd.concat(stock_long, ignore_index=True)
    stock_data = stock_data.dropna()

    stock_data.to_sql('stock_prices', conn, if_exists='replace', index=False)
    print(f"✓ Inserted {len(stock_data)} stock price records")

"""CRYPTOCURRENCIES QUERIES"""

# check if data exists in the table
cursor.execute("SELECT COUNT(*) FROM cryptocurrencies")
print("Row count:", cursor.fetchone())

# Check what tables exist
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
print("Tables:", cursor.fetchall())

# Insert crypto_df into the cryptocurrencies table
import pandas as pd


print("crypto_df columns:", crypto_df.columns.tolist())
print("crypto_df shape:", crypto_df.shape)
print(crypto_df.head(2))

crypto_insert = crypto_df[['id', 'symbol', 'name', 'current_price',
                            'market_cap', 'market_cap_rank',
                            'total_volume', 'circulating_supply',
                            'total_supply', 'ath', 'atl']].copy()


crypto_insert.to_sql('cryptocurrencies', conn, if_exists='replace', index=False)
conn.commit()

print(f"✓ Inserted {len(crypto_insert)} records into cryptocurrencies table")

cursor.execute("""
SELECT
    name,
    symbol,
    market_cap,
    market_cap_rank,
    current_price
FROM cryptocurrencies
ORDER BY market_cap_rank
LIMIT 3;
""")

results = cursor.fetchall()
print("Results:", results)


df_result = pd.read_sql_query("""
    SELECT name, symbol, market_cap, market_cap_rank, current_price
    FROM cryptocurrencies
    ORDER BY market_cap_rank
    LIMIT 3
""", conn)

print(df_result)

cursor.execute("""
SELECT
    name,
    symbol,
    circulating_supply,
    total_supply,
    ROUND((circulating_supply * 100.0 / NULLIF(total_supply, 0)), 2) as supply_percentage
FROM cryptocurrencies
WHERE total_supply > 0
    AND (circulating_supply * 100.0 / total_supply) > 90
ORDER BY supply_percentage DESC;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    name,
    symbol,
    current_price,
    ath,
    ROUND((current_price * 100.0 / ath), 2) as percent_of_ath
FROM cryptocurrencies
WHERE ath > 0
    AND (current_price * 100.0 / ath) >= 90
ORDER BY percent_of_ath DESC;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    ROUND(AVG(market_cap_rank), 2) as avg_market_cap_rank,
    COUNT(*) as coin_count,
    MIN(market_cap_rank) as best_rank,
    MAX(market_cap_rank) as worst_rank
FROM cryptocurrencies
WHERE total_volume > 1000000000;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    name,
    symbol,
    current_price,
    market_cap,
    market_cap_rank as last_updated
FROM cryptocurrencies
ORDER BY market_cap_rank ASC
LIMIT 1;
""")
cursor.fetchall()

"""CRYPTO_PRICES QUERIES"""

#  Check if data exists in crypto_prices
cursor.execute("SELECT COUNT(*) FROM crypto_prices")
print("crypto_prices row count:", cursor.fetchone())


cursor.execute("PRAGMA table_info(crypto_prices)")
print("\nColumns:", cursor.fetchall())


print("\ncombine3coins_df shape:", combine3coins_df.shape)
print("combine3coins_df columns:", combine3coins_df.columns.tolist())
print(combine3coins_df.head())

crypto_prices_df = combine3coins_df.rename(columns={
    'price_inr': 'price_usd'  # rename price_inr to price_usd
})


print("Unique coin_ids:", crypto_prices_df['coin_id'].unique())
print("Date range:", crypto_prices_df['date'].min(), "to", crypto_prices_df['date'].max())

# Insert into table
crypto_prices_df.to_sql('crypto_prices', conn, if_exists='replace', index=False)
conn.commit()
print(f"✓ Inserted {len(crypto_prices_df)} records into crypto_prices!")

INR_TO_USD = 84

crypto_prices_df = combine3coins_df.copy()
crypto_prices_df['price_usd'] = (combine3coins_df['price_inr'] / INR_TO_USD).round(6)
crypto_prices_df = crypto_prices_df.drop(columns=['price_inr'])

print("✓ Converted INR to USD")
print(crypto_prices_df.head())

cursor.execute("SELECT MIN(date), MAX(date) FROM crypto_prices WHERE coin_id = 'bitcoin'")
print("Bitcoin date range:", cursor.fetchone())


cursor.execute("""
SELECT
    MAX(price_usd) as highest_price,
    date
FROM crypto_prices
WHERE coin_id = 'bitcoin'
    AND date >= date('now', '-365 days')
GROUP BY date
ORDER BY highest_price DESC
LIMIT 1;
""")

cursor.fetchall()

cursor.execute("""
SELECT
    coin_id,
    ROUND(AVG(price_usd), 2) as avg_price,
    MIN(price_usd) as min_price,
    MAX(price_usd) as max_price,
    COUNT(*) as days_count
FROM crypto_prices
WHERE coin_id = 'ethereum'
    AND date >= date('now', '-1 year')
GROUP BY coin_id;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    date,
    price_usd,
    LAG(price_usd) OVER (ORDER BY date) as prev_price,
    ROUND(price_usd - LAG(price_usd) OVER (ORDER BY date), 2) as price_change
FROM crypto_prices
WHERE coin_id = 'bitcoin'
    AND date >= '2025-01-01'
    AND date < '2025-02-01'
ORDER BY date;
""")

cursor.fetchall()

cursor.execute("""
SELECT
    coin_id,
    ROUND(AVG(price_usd), 2) as avg_price,
    COUNT(*) as days_count
FROM crypto_prices
WHERE date >= date('now', '-1 year')
GROUP BY coin_id
ORDER BY avg_price DESC
LIMIT 1;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    MAX(CASE WHEN date >= '2024-09-01' AND date < '2024-10-01' THEN price_usd END) as sep_2024_price,
    MAX(CASE WHEN date >= '2025-09-01' AND date < '2025-10-01' THEN price_usd END) as sep_2025_price,
    ROUND(
        ((MAX(CASE WHEN date >= '2025-09-01' AND date < '2025-10-01' THEN price_usd END) -
          MAX(CASE WHEN date >= '2024-09-01' AND date < '2024-10-01' THEN price_usd END)) * 100.0 /
          NULLIF(MAX(CASE WHEN date >= '2024-09-01' AND date < '2024-10-01' THEN price_usd END), 0)), 2
    ) as percent_change
FROM crypto_prices
WHERE coin_id = 'bitcoin';
""")
cursor.fetchall()

"""OIL_PRICES QUERIES"""

oil_df.to_sql('oil_prices', conn, if_exists='replace', index=False)

cursor.execute("SELECT COUNT(*) FROM oil_prices")
print(cursor.fetchall())


cursor.execute("SELECT MIN(date), MAX(date) FROM oil_prices")
print(cursor.fetchall())

cursor.execute("""
SELECT
    MAX(price) as highest_price,
    date
FROM oil_prices
WHERE date >= date('now', '-5 years')
GROUP BY date
ORDER BY highest_price DESC
LIMIT 1;
""")

results = cursor.fetchall()
print(results)

cursor.execute("""
SELECT
    strftime('%Y', date) as year,
    ROUND(AVG(price), 2) as avg_price,
    MIN(price) as min_price,
    MAX(price) as max_price
FROM oil_prices
GROUP BY year
ORDER BY year DESC;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    date,
    price,
    LAG(price) OVER (ORDER BY date) as prev_price,
    ROUND(price - LAG(price) OVER (ORDER BY date), 2) as daily_change
FROM oil_prices
WHERE date >= '2020-03-01'
    AND date <= '2020-04-30'
ORDER BY date;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    MIN(price) as lowest_price,
    date
FROM oil_prices
WHERE date >= date('now', '-10 years')
GROUP BY date
ORDER BY lowest_price ASC
LIMIT 1;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    strftime('%Y', date) as year,
    MAX(price) - MIN(price) as volatility,
    MAX(price) as max_price,
    MIN(price) as min_price
FROM oil_prices
GROUP BY year
ORDER BY volatility DESC;
""")
cursor.fetchall()

"""STOCK_PRICES QUERIES"""

stocks_long_df.to_sql('stock_prices', conn, if_exists='replace', index=False)
conn.commit() # Commit changes to the database
print(f"✓ Inserted {len(stocks_long_df)} records into stock_prices table")

cursor.execute("PRAGMA table_info(stock_prices)")
print(cursor.fetchall())

cursor.execute("""
SELECT
    date,
    ticker,
    open,
    high,
    low,
    close,
    volume
FROM stock_prices
WHERE ticker = '^IXIC'
ORDER BY date DESC
LIMIT 10;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    MAX(close) as highest_close,
    date
FROM stock_prices
WHERE ticker = '^IXIC'
GROUP BY date
ORDER BY highest_close DESC
LIMIT 1;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    date,
    ticker,
    high,
    low,
    ROUND(high - low, 2) as price_difference,
    close
FROM stock_prices
WHERE ticker = '^GSPC'
ORDER BY (high - low) DESC
LIMIT 5;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    ticker,
    strftime('%Y-%m', date) as month,
    ROUND(AVG(close), 2) as avg_close,
    COUNT(*) as trading_days
FROM stock_prices
GROUP BY ticker, month
ORDER BY ticker, month DESC;

""")
cursor.fetchall()

cursor.execute("""
SELECT
    ticker,
    ROUND(AVG(volume), 0) as avg_volume,
    MIN(volume) as min_volume,
    MAX(volume) as max_volume
FROM stock_prices
WHERE ticker = '^NSEI'
    AND date >= '2024-01-01'
    AND date < '2025-01-01'
GROUP BY ticker;
""")
cursor.fetchall()

"""JOIN QUERIES (CROSS-MARKET ANALYSIS)"""

# Check if tables exist and have data
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
print("Tables:", cursor.fetchall())


cursor.execute("SELECT COUNT(*) FROM crypto_prices")
print("Crypto rows:", cursor.fetchall())

cursor.execute("SELECT COUNT(*) FROM oil_prices")
print("Oil rows:", cursor.fetchall())

cursor.execute("SELECT COUNT(*) FROM stock_prices")
print("Stock rows:", cursor.fetchall())

# Check crypto_prices date format and range
cursor.execute("SELECT MIN(date), MAX(date) FROM crypto_prices WHERE coin_id = 'bitcoin'")
print("Crypto dates:", cursor.fetchall())

# Check oil_prices date format and range
cursor.execute("SELECT MIN(Date), MAX(Date) FROM oil_prices")
print("Oil dates:", cursor.fetchall())


cursor.execute("SELECT date FROM crypto_prices WHERE coin_id = 'bitcoin' LIMIT 3")
print("Crypto sample dates:", cursor.fetchall())

cursor.execute("SELECT Date FROM oil_prices LIMIT 3")
print("Oil sample dates:", cursor.fetchall())

cursor.execute("""
SELECT
    cp.date,
    cp.price_usd as bitcoin_price,
    op.Price as oil_price
FROM crypto_prices cp
INNER JOIN oil_prices op ON cp.date = DATE(op.Date)
WHERE cp.coin_id = 'bitcoin'
    AND cp.date >= '2025-01-01'
    AND cp.date < '2026-01-01'
ORDER BY cp.date;
""")

cursor.fetchall()

cursor.execute("""
SELECT
    cp.date,
    cp.price_usd as bitcoin_price,
    sp.close as sp500_price
FROM crypto_prices cp
INNER JOIN stock_prices sp ON cp.date = DATE(sp.date)
WHERE cp.coin_id = 'bitcoin'
    AND sp.ticker = '^GSPC'
    AND cp.date >= '2025-01-01'
    AND cp.date < '2026-01-01'
ORDER BY cp.date;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    cp.date,
    cp.price_usd as ethereum_price,
    sp.close as nasdaq_price
FROM crypto_prices cp
INNER JOIN stock_prices sp ON cp.date = DATE(sp.date)
WHERE cp.coin_id = 'ethereum'
    AND sp.ticker = '^IXIC'
    AND cp.date >= '2025-01-01'
    AND cp.date < '2026-01-01'
ORDER BY cp.date;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    Date,
    oil_price,
    prev_oil_price,
    oil_change,
    bitcoin_price,
    prev_bitcoin_price,
    bitcoin_change
FROM (
    SELECT
        op.Date,
        op.Price as oil_price,
        LAG(op.Price) OVER (ORDER BY op.Date) as prev_oil_price,
        op.Price - LAG(op.Price) OVER (ORDER BY op.Date) as oil_change,
        cp.price_usd as bitcoin_price,
        LAG(cp.price_usd) OVER (ORDER BY cp.date) as prev_bitcoin_price,
        cp.price_usd - LAG(cp.price_usd) OVER (ORDER BY cp.date) as bitcoin_change
    FROM oil_prices op
    INNER JOIN crypto_prices cp ON DATE(op.Date) = cp.date
    WHERE cp.coin_id = 'bitcoin'
) subquery
WHERE oil_change > 5
ORDER BY Date;
""")

cursor.fetchall()

cursor.execute("""
SELECT
    cp.date,
    cp.coin_id,
    cp.price_usd as crypto_price,
    sp.close as nifty_price
FROM crypto_prices cp
INNER JOIN stock_prices sp ON cp.date = DATE(sp.date)
WHERE cp.coin_id IN ('bitcoin', 'ethereum', 'tether')
    AND sp.ticker = '^NSEI'
    AND cp.date >= '2025-01-01'
    AND cp.date < '2026-01-01'
ORDER BY cp.date, cp.coin_id;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    sp.date,
    sp.close as gspc_price,
    op.Price as oil_price
FROM stock_prices sp
INNER JOIN oil_prices op ON DATE(sp.date) = DATE(op.Date)
WHERE sp.ticker = '^GSPC'
    AND sp.date >= '2025-01-01'
    AND sp.date < '2026-01-01'
ORDER BY sp.date;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    cp.date,
    cp.price_usd as bitcoin_price,
    op.Price as oil_price
FROM crypto_prices cp
INNER JOIN oil_prices op ON cp.date = DATE(op.Date)
WHERE cp.coin_id = 'bitcoin'
    AND cp.date >= '2025-01-01'
    AND cp.date < '2026-01-01'
ORDER BY cp.date;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    sp.date,
    sp.close as nasdaq_price,
    cp.price_usd as ethereum_price
FROM stock_prices sp
INNER JOIN crypto_prices cp ON DATE(sp.date) = cp.date
WHERE sp.ticker = '^IXIC'
    AND cp.coin_id = 'ethereum'
    AND sp.date >= '2025-01-01'
    AND sp.date < '2026-01-01'
ORDER BY sp.date;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    cp.date,
    cp.coin_id,
    cp.price_usd as crypto_price,
    sp.ticker as stock_ticker,
    sp.close as stock_price
FROM crypto_prices cp
INNER JOIN stock_prices sp ON cp.date = DATE(sp.date)
WHERE cp.coin_id IN ('bitcoin', 'ethereum', 'tether')
    AND sp.ticker IN ('^IXIC', '^GSPC', '^NSEI')
    AND cp.date >= '2025-01-01'
    AND cp.date < '2026-01-01'
ORDER BY cp.date, cp.coin_id, sp.ticker;
""")
cursor.fetchall()

cursor.execute("""
SELECT
    cp.date,
    cp.price_usd as bitcoin_price,
    op.Price as oil_price,
    sp.close as stock_price,
    sp.ticker as stock_ticker
FROM crypto_prices cp
INNER JOIN oil_prices op ON cp.date = DATE(op.Date)
INNER JOIN stock_prices sp ON cp.date = DATE(sp.date)
WHERE cp.coin_id = 'bitcoin'
    AND sp.ticker = '^GSPC'
    AND cp.date >= '2025-01-01'
    AND cp.date < '2026-01-01'
ORDER BY cp.date;
""")
cursor.fetchall()

"""Streamlit"""

conn.close()
print("✓ Done!")

import sqlite3

# Connect to a FILE (not in-memory)
conn = sqlite3.connect('/content/market_data.db')
cursor = conn.cursor()

# Recreate all tables
cursor.execute("""
CREATE TABLE IF NOT EXISTS cryptocurrencies (
    id TEXT, symbol TEXT, name TEXT,
    current_price REAL, market_cap REAL,
    market_cap_rank INTEGER, total_volume REAL,
    circulating_supply REAL, total_supply REAL,
    ath REAL, atl REAL
)""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS crypto_prices (
    coin_id TEXT, date TEXT, price_usd REAL
)""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS oil_prices (
    Date TEXT, Price REAL
)""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS stock_prices (
    date TEXT, ticker TEXT, open REAL,
    high REAL, low REAL, close REAL, volume REAL
)""")

conn.commit()
print("✓ Tables created!")

# Insert all dataframes into the database
crypto_df.to_sql('cryptocurrencies', conn, if_exists='replace', index=False)
print(f"✓ Inserted {len(crypto_df)} crypto records")

crypto_prices_df.to_sql('crypto_prices', conn, if_exists='replace', index=False)
print(f"✓ Inserted {len(crypto_prices_df)} crypto price records")

oil_df.to_sql('oil_prices', conn, if_exists='replace', index=False)
print(f"✓ Inserted {len(oil_df)} oil price records")

stocks_long_df.to_sql('stock_prices', conn, if_exists='replace', index=False)
print(f"✓ Inserted {len(stocks_long_df)} stock price records")

conn.commit()
conn.close()
print("\n✅ Database saved to /content/market_data.db!")

from google.colab import files
files.download('/content/market_data.db')
print("✓ Downloading...")